driver:
 name: docker
 binary: docker
 use_sudo: false

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.5.1-1

platforms:
- name: centos-7.3
  driver_config:
    image: centos:centos7
    run_command: /usr/sbin/init
    privileged: true

suites:
  - name: default
    run_list:
       - recipe[pagerduty_agent::default]
    attributes:
